#define IDC_STATIC                      9
#define IDD_LUA                         10
#define IDC_BUTTON_LUABROWSE            11
#define IDC_BUTTON_LUARUN               12
#define IDC_BUTTON_LUASTOP              13
#define IDC_EDIT_LUAPATH                14
#define IDC_LUACONSOLE                  15
#define IDC_BUTTON_LUAEDIT              16
#define ID_LUA_OPEN                     17
#define ID_LUA_CLOSE_ALL                18
#define IDC_LUACONSOLE_CHOOSEFONT       19
#define IDC_LUACONSOLE_CLEAR            20
