#define IDC_STATIC                      9
#define IDD_LUA                         10
#define IDC_BUTTON_LUABROWSE            11
#define IDC_BUTTON_LUARUN               12
#define IDC_BUTTON_LUASTOP              13
#define IDC_EDIT_LUAPATH                14
#define IDC_LUACONSOLE                  15
#define IDC_BUTTON_LUAEDIT              16
#define ID_LUA_OPEN                     17
#define ID_LUA_CLOSE_ALL                18
#define IDC_LUACONSOLE_CHOOSEFONT       19
#define IDC_LUACONSOLE_CLEAR            20

#define IDD_REPLAYINP                   234
#define IDD_RECORDINP                   235
#define IDD_RAMSEARCH                   236
#define IDD_RAMWATCH                    237
#define IDD_EDITWATCH                   238
#define IDD_PROMPT                      239
#define IDR_RWACCELERATOR               240
#define RAMMENU_FILE_AUTOLOAD           11800
#define RAMMENU_FILE_SAVEWINDOW         11801
#define RAMMENU_FILE_SAVE               11802
#define RAMMENU_FILE_SAVEAS             11803
#define RAMMENU_FILE_OPEN               11804
#define RAMMENU_FILE_APPEND             11805
#define RAMMENU_FILE_NEW                11806
#define RAMMENU_FILE_RECENT             11807
#define ID_RAM_SEARCH                   11808
#define ID_RAM_WATCH                    11809
#define RW_MENU_FIRST_RECENT_FILE       11810
#define RW_MENU_LAST_RECENT_FILE        11811
#define IDC_CHOOSE_LIST                 20076
#define IDC_LENGTH                      20255
#define IDC_FRAMES                      20256
#define IDC_UNDO                        20257
#define IDC_METADATA                    20258
#define IDC_READONLY                    20259
#define IDC_FILENAME                    20260
#define IDC_BROWSE                      20261
#define IDC_REPLAYRESET                 20262
#define IDC_RAMLIST                     20266
#define IDC_C_SEARCH                    20267
#define IDC_C_WATCH                     20269
#define IDC_C_RESET                     20270
#define IDC_C_ELIMINATE                 20271
#define IDC_LESSTHAN                    20272
#define IDC_MORETHAN                    20273
#define IDC_NOMORETHAN                  20274
#define IDC_NOLESSTHAN                  20275
#define IDC_EQUALTO                     20276
#define IDC_DIFFERENTFROM               20277
#define IDC_DIFFERENTBY                 20278
#define IDC_MODULO                      20279
#define IDC_EDIT_DIFFBY                 20280
#define IDC_EDIT_MODBY                  20281
#define IDC_PREVIOUSVALUE               20282
#define IDC_SPECIFICVALUE               20283
#define IDC_SPECIFICADDRESS             20284
#define IDC_NUMBEROFCHANGES             20285
#define IDC_EDIT_COMPAREVALUE           20286
#define IDC_EDIT_COMPAREADDRESS         20287
#define IDC_EDIT_COMPARECHANGES         20288
#define IDC_SIGNED                      20289
#define IDC_UNSIGNED                    20290
#define IDC_HEX                         20291
#define IDC_C_AUTOSEARCH                20292
#define IDC_1_BYTE                      20293
#define IDC_2_BYTES                     20294
#define IDC_4_BYTES                     20295
#define IDC_MISALIGN                    20296
#define IDC_C_RESET_CHANGES             20297
#define IDC_C_UNDO                      20298
#define IDC_WATCHLIST                   20299
#define IDC_C_WATCH_EDIT                20300
#define IDC_C_WATCH_REMOVE              20301
#define IDC_C_WATCH_DUPLICATE           20302
#define ID_WATCHES_UPDOWN               20303
#define IDC_C_WATCH_UP                  20304
#define IDC_C_WATCH_DOWN                20305
#define IDC_PROMPT_TEXT                 20306
#define IDC_PROMPT_TEXT2                20307
#define IDC_PROMPT_EDIT                 20308
